##################################################################################
##############################                        ############################
############################## A U T O M A T I O N S  ############################
##############################                        ############################
##################################################################################

##################################################################################
################################   ALARM AWAY   ##################################
##################################################################################

- alias: 'Alarm Away'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      to: 'on'
    - platform: state
      entity_id: binary_sensor.patio_door_opened
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.stoffels_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.stoffels_alarm
    - service: switch.turn_on
      entity_id: switch.siren
#
##################################################################################
###############################   ALARM IN HOME   ################################
##################################################################################

- alias: 'Alarm Home'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      to: 'on'
    - platform: state
      entity_id: binary_sensor.patio_door_opened
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.stoffels_alarm
      state: armed_home
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.stoffels_alarm
    - service: switch.turn_on
      entity_id: switch.siren
#
##################################################################################
#########################   LIGHT FLASH / SIREN ON   #############################
##################################################################################

- alias: Flash Lights
  hide_entity: True
  trigger:
    platform: state
    entity_id: alarm_control_panel.stoffels_alarm
    to: 'triggered'
  action:
    - service: script.turn_on
      entity_id:
        - script.light_flash
        - script.siren
    - service: notify.jizar
      data:
        title: Alarm Triggered
        message: The alarm in the is on
#
##################################################################################
#########################   LIGHT FLASH / SIREN OFF   ############################
##################################################################################

- alias: Disarm
  hide_entity: True
  trigger:
    platform: state
    entity_id: alarm_control_panel.stoffels_alarm
    to: 'disarmed'
  action:
    - service: script.turn_off
      entity_id:
        - script.light_loop
        - script.siren_loop
        - script.light_flash
        - script.siren
    - service: switch.turn_off
      entity_id: switch.siren
    - service: notify.jizar
      data:
        title: Alarm Disarmed
        message: The alarm in the is Disarmed
#
##################################################################################
#################################### BACK DOOR ###################################
##################################################################################

- alias: back door
  trigger:
  - platform: state
    entity_id: binary_sensor.patio_door_opened
    to: 'on'
  
  condition:
    - condition: state
      entity_id: alarm_control_panel.stoffels_alarm
      state: disarmed
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.google_assistant
        media_content_id: http://192.168.1.41:8123/local/waves/backdoor.mp3
        media_content_type: music
    - service: tts.google_say
      entity_id: media_player.google_assistant
      data:
        message: Back door Open
#
##################################################################################
################################### FRONT DOOR ###################################
##################################################################################

- alias: front door
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_opened
    to: 'on'
  action:
    service: tts.google_say
    entity_id: media_player.google_assistant
    data:
      message: Front door open
#
##################################################################################
################################## GARAGE DOOR ###################################
##################################################################################

- alias: garage door open
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: open
  action:
    service: tts.google_say
    entity_id: media_player.google_assistant
    data:
      message: Garage Door Opened
#
- alias: garage door closed
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: closed
  action:
    service: tts.google_say
    entity_id: media_player.google_assistant
    data:
      message: Garage Door Closed
#
##################################################################################
####################################    MAIL   ###################################
##################################################################################

- alias: delivery
  trigger:
    platform: numeric_state
    entity_id: sensor.deliveries_today
    above: 0
  # condition:
    # - condition: template
      # value_template: '{{trigger.to_state.state|int > trigger.from_state.state|int}}'
    # - condition: state
      # entity_id: group.all_devices
      # state: 'home'
  action:
    service: tts.google_say
    entity_id: media_player.google_assistant
    data_template:
     message: "You got {{ states.sensor.deliveries_today.state }} Mail"
#
##################################################################################
####################################  TIMERS  ####################################
##################################################################################
#
- alias: hourly
  trigger:
  - platform: time
    minutes: 00
    seconds: 01
  condition:
    condition: time
    after: '08:00:00'
    before: '22:00:00'
  action:
  - service: media_player.play_media
    data_template:
      entity_id: media_player.google_assistant
      media_content_id: /local/waves/chime{{now().strftime("%I")}}.wav
      media_content_type: music
  - service: tts.google_say
    entity_id: media_player.google_assistant
    data_template:
      message: Its {{now().strftime("%I %p")}}
      cache: true
  - delay: '00:00:26'
#
- alias: 10 PM
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - service: tts.google_say
    entity_id: media_player.google_assistant
    data:
      message: It's 10 pm master, Starting Sleep mode.
  - service: light.turn_off
    entity_id:
    - light.laundry
    - light.boys_room
  - service: light.turn_on
    entity_id: light.hallway
    data:
      brightness: 50
  - service: switch.turn_off
    entity_id:
    - switch.blue_rope
    - switch.red_rope
    - switch.dinning_room
    - switch.kitchen
#
- alias: 7:30 am
  trigger:
  - platform: time
    at: 07:30:00
  action:
  - service: tts.google_say
    entity_id: media_player.google_assistant
    data:
      message: It's 7:30 AM, Starting wake up mode.
  - service: light.turn_off
    entity_id:
    - light.hallway
  - service: switch.turn_on
    entity_id:
    - switch.kitchen
    - switch.51
#
- alias: Boys TV
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: time
    after: "22:00:00"
    before: "23:30:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - sun
  action:
  - service: switch.turn_off
    entity_id:
    - switch.boys_tv
#
- alias: Game on
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
    condition: time
    after: "17:00:00"
    before: "19:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: switch.turn_on
    entity_id:
    - switch.computer
#
- alias: Game off
  trigger:
  - platform: time
    at: '19:00:00'
  condition:
    condition: time
    after: "19:00:00"
    before: "20:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: switch.turn_of
    entity_id:
    - switch.computer
#
- alias: Scarlett
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
    condition: time
    after: "22:00:00"
    before: "23:30:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - sun
  action:
  - service: switch.turn_off
    entity_id:
    - switch.master
#
- alias: Boys Alarm
  trigger:
  - platform: time
    at: '06:15:00'
  condition:
    condition: time
    after: "05:00:00"
    before: "07:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: light.turn_on
    entity_id:
    - switch.boys_room
##################################################################################
####################################  CAMERAS  ###################################
##################################################################################

# - alias: mycam
  # id: '1499290448978'
  # trigger:
  # - entity_id: image_processing.id_tester   ######### WAIT FOR MICROSOFT FACE TO UPDATE QUOTA ############
    # platform: state
    # to: Jizar Stoffel
  # action:
  # - service: switch.toggle
    # entity_id: switch.blue
  # - service: tts.google_say
    # entity_id: media_player.google_assistant
    # data:
      # message: Hello Master, I see you at your computer. Would you like some relaxing music while you are working? 
#
# - alias: Ipcam
  # trigger:
  # - entity_id: image_processing.id_ipcam
    # platform: state
    # to: Jizar Stoffel
  # action:
  # - service: switch.turn_on
    # entity_id: switch.dinning_room
  # - service: tts.google_say
    # entity_id: media_player.google_assistant
    # data:
      # message: Turning Dinning room lights on for you Master.
 #
##################################################################################
##################################  DETECTION  ###################################
##################################################################################

- alias: detection
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_motion
    to: 'off'
    for:
      minutes: 5
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen
#
##################################################################################
##################################     TEMP    ###################################
##################################################################################

- alias: NoAC
  trigger:
    - platform: numeric_state
      entity_id: sensor.motion_sensor_temperature
      above: 85
  action:
  - service: tts.google_say
    entity_id: media_player.google_assistant
    data_template:
      message: The Temperature is  {{ states.sensor.motion_sensor_temperature.state }} degrees. Please check the AC for problems.
- alias: tempup
  trigger:
    - platform: numeric_state
      entity_id: sensor.motion_sensor_temperature
      above: 84
  action:
    service: tts.google_say
    entity_id: media_player.google_assistant
    data_template:
      message: The Temperature is now higher than {{ states.sensor.motion_sensor_temperature.state }} degrees.
#
- alias: tempdown
  trigger:
    - platform: numeric_state
      entity_id: sensor.motion_sensor_temperature
      below: 72
  condition:
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
  action:
    service: tts.google_say
    entity_id: media_player.google_assistant
    data_template:
        message: The Temperature is now below than {{ states.sensor.motion_sensor_temperature.state }} degrees.
        
#
##################################################################################
################################     TRACKING    #################################
##################################################################################     
- alias: zones
  trigger:
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.bschool
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.sschool
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.dina
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.joan
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.connie
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.connieapt
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.janice
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.leona
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.lisa
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.diane
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.kelly
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.alison
    event: enter
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.evelin
    event: enter
############################### LEAVE ##############################
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.bschool
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.sschool
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.dina
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.joan
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.connie
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.connieapt
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.janice
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.leona
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.lisa
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.diane
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.kelly
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.alison
    event: leave
  - platform: zone
    entity_id: device_tracker.jizar_nil, device_trackert.jizar_jizar, sensor.nil, sensor.jizar
    zone: zone.evelin
    event: leave
  action:     
  - service: notify.jizar
    data_template:
      message: "{{ trigger.to_state.name }} is in {{ trigger.to_state.state }}"