homeassistant:
  name: Stoffel's Home Assistant
  latitude: !secret homelat
  longitude: !secret homelon
  elevation: 435
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
#
#################################################################################
####################################   DEFAULTS   ###############################
#################################################################################

config:
updater:
discovery:
conversation:
history:
logbook:
sun:

#################################################################################
####################################   INCLUDES   ###############################
#################################################################################

automation: !include automations.yaml
camera: !include cameras.yaml
device_tracker: !include devicetracker.yaml
group: !include groups.yaml
#image_processing: !include imgpro.yaml
media_player: !include players.yaml
panel_iframe: !include panels.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
#shell_command: !include shellcommand.yaml
switch: !include switches.yaml
zone: !include zones.yaml

#################################################################################
####################################   CUSTOMS    ###############################
#################################################################################

frontend:
 themes:
   purple:
     primary-color: "#6600cc"
   black:
     primary-color: black
#
zwave:
  usb_path: /dev/ttyACM0
#
tts:
  - platform: google
    # cache: true
    # cache_dir: /tmp/tts
    # time_memory: 300
#
http:
  # api_password: !secret api_password
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # base_url: !secret base_url 

#
mqtt:
  broker: 192.168.1.41
  port: 1883
  username: !secret username
  password: !secret password
#
wink:
  email: !secret email
  password: !secret wink_pass
#
alarm_control_panel:
  - platform: manual
    name: Stoffel's Alarm
   # code: !secret alarmcode
    pending_time: 5
    trigger_time: 5
    disarm_after_trigger: false
#
ifttt:
  key: !secret ifttt_key

notify:
  - platform: pushbullet
    name: Jizar
    api_key: !secret pushbulletapi
#
# emulated_hue:
  # listen_port: 80