homeassistant:
  name: Stoffel's Home Assistant
  latitude: !secret homelat
  longitude: !secret homelon
  elevation: 435
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
#
#################################################################################
####################################   DEFAULTS   ###############################
#################################################################################

config:
updater:
discovery:
conversation:
history:
logbook:
sun:
map:
wink:

#################################################################################
####################################   INCLUDES   ###############################
#################################################################################

automation: !include automations.yaml
camera: !include cameras.yaml
device_tracker: !include devicetracker.yaml
group: !include groups.yaml
#image_processing: !include imgpro.yaml
media_player: !include players.yaml
panel_iframe: !include panels.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
#shell_command: !include shellcommand.yaml
switch: !include switches.yaml
zone: !include zones.yaml
binary_sensor: !include binary_sensors.yaml
light: !include light.yaml

#################################################################################
####################################   CUSTOMS    ###############################
#################################################################################

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
#
frontend: !include frontend.yaml
#
zwave:
  usb_path: /dev/ttyACM0
#
google_assistant:
  project_id: !secret project_id
  client_id: !secret project_id
  access_token: !secret access_token
  agent_user_id: !secret email
  api_key: !secret gaapi_key
  exposed_domains:
    - switch
    - light
#
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
#
http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 3
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # base_url: !secret base_url 

#
mqtt:
  broker: 192.168.1.41
  port: 1883
  username: !secret username
  password: !secret password
#
alarm_control_panel:
  - platform: manual
    name: Stoffel's Alarm
    code: !secret alarmcode
    pending_time: 5
    trigger_time: 5
    disarm_after_trigger: false
#
notify:
  - platform: pushbullet
    name: Jizar
    api_key: !secret pushbulletapi
#
customizer:
  custom_ui: local
  hide_attributes:
    - node_id
    - value_index
#
octoprint:
  host: 192.168.1.4
  api_key: !secret opapi_key
  bed: true
  number_of_tools: 1
  