###########################  ICLOUD  ####################

# - platform: icloud
  # username: !secret iclouduser
  # password: !secret icloudpass
  # account_name: !secret icloudacc

########################  My phone  #######################

- platform: owntracks_http
  max_gps_accuracy: 200
  waypoints: true

############################################################

# - platform: netgear
  # host: 192.168.1.1
  # username: !secret nguser
  # password: !secret ngpass
  # track_new_devices: false
  
- platform: mqtt
  devices:
    jizar: /location/jizar
    nil: /location/nil
    scarlett: /location/scarlett
    nenem: /location/nenem
    
# - platform: bluetooth_tracker