# 1
default_view:
  view: true
  name: Default View
  icon: mdi:home
  entities: 
  - group.temperature
  - group.tracker
  - sensor.ram_free
  - sensor.energy_meter_energy
  - sensor.yr_symbol
  - sensor.motion_sensor_temperature
  - group.weather
  - group.time
  - group.deliveries
  - group.alarm
  - alarm_control_panel.stoffels_alarm
  - group.lights
  - group.switches
  - camera.usps_mail
  - customizer.customizer
  - updater.updater
  - group.ms1
  - group.ms2
  - group.ms3
  - group.ms4
# 2
camera_view:
  view: true
  name: Cameras
  icon: mdi:cctv
  entities:
  - group.image_processing
  - microsoft_face.stoffels
  - group.cameras
  - group.maps
# 3
lights_view:
  view: true
  icon: mdi:lightbulb
  name: Lights
  entities:
  - group.lights
  - group.switches
players_view:
  view: true
  name: Media Players
  icon: mdi:play
  entities:
  - group.players
Family_room_view:
  view: true
  name: Family Room
  icon: mdi:sofa
  entities:
  - switch.sonoff56
  - remote.harmony_hub
  - media_player.googlebox
bedrooms_view:
  view: true
  name: Family Room
  icon: mdi:hotel
  entities:
  - switch.master
  - light.master_bedroom_light
  - light.boys_light
  - switch.sonoff59
power_view:
  view: true
  name: Power Meter
  icon: mdi:power-settings
  entities:
  - group.energy_meter
automations_view:
  view: true
  name: Automations
  icon: mdi:home-automation
  entities:
  - group.automations
  - script.temperature
  - script.ms1on
  - script.ms1off
  - script.lights_off
octoprint_view:
  view: true
  name: OctoPrint
  icon: mdi:printer-3d
  entities:
  - group.octoprint
#################################################################################################
############################################# GROUPS ############################################
#################################################################################################
# A
alarm:
  name: Alarm System
  icon: mdi:alarm-light
  entities:
  - cover.garage_door
  - binary_sensor.motion_sensor_motion
  - binary_sensor.patio_door_opened
  - binary_sensor.front_door_opened
  - alarm_control_panel.stoffels_alarm
  - automation.alarm_away
  - automation.alarm_home
  - automation.flash_lights
  - automation.detection
  - automation.disarm
automations:
  name: Automations
  icon: mdi:home-automation
  entities:
  - automation.3d_printer_off
  - automation.outside_lights_off
  - automation.outside_lights_on
  - automation.Outside_off_during_the_day
  - automation.closet_off
  - automation.low_temp
  - automation.zones
  - automation.hourly
  - automation.alarm_away
  - automation.alarm_home
  - automation.flash_lights
  - automation.detection_on
  - automation.detection_off
  - automation.disarm
  - automation.10_pm
  - automation.730_am
  - automation.boys_tv
  - automation.back_door
  - automation.front_door
  - automation.garage_door_closed
  - automation.garage_door_open
  - automation.mycam
  - automation.ipcam
  - automation.noac
  - automation.tempup
  - automation.tempdown
  - automation.update
  - automation.delivery
  - automation.boys_alarm
  - automation.scarlett
  - automation.game_on
  - automation.game_off
  - automation.boys_detection_on
  - automation.boys_detection_off
# B
binary_sensor:
  name: Binary Sensors
  icon: mdi:wifi
  entities:
  - binary_sensor.front_door_opened
  - binary_sensor.motion_sensor_motion
  - binary_sensor.patio_door_opened
  - binary_sensor.philips_hue_2
  - binary_sensor.wink_hub_2
# C
cameras:
  name: Cameras
  icon: mdi:cctv
  entities:
  - camera.main_area
  - camera.ip_camera
  - camera.usps_mail
climate:
  name: Climate
  icon: mdi:climate
  entities:
  - sensor.motion_sensor_temperature
# D
Deliveries:
  - sensor.usps_mail
  - sensor.usps_packages
  - sensor.ups
  - sensor.fedex
  - sensor.deliveries_today
  - sensor.packages_in_transit
# E
energy_meter:
  name: Energy Meter
  icon: mdi:power
  entities:
  - zwave.aeotec_zw090_zstick_gen5_us
  - zwave.aeotec_dsb09104_home_energy_meter
  - sensor.aeotec_dsb09104_home_energy_meter_energy
  - sensor.aeotec_dsb09104_home_energy_meter_energy_2
  # - sensor.aeotec_dsb09104_home_energy_meter_energy_3
  # - sensor.aeotec_dsb09104_home_energy_meter_exporting
  # - sensor.aeotec_dsb09104_home_energy_meter_exporting_2
  # - sensor.aeotec_dsb09104_home_energy_meter_exporting_3
  # - sensor.aeotec_dsb09104_home_energy_meter_interval
  # - sensor.aeotec_dsb09104_home_energy_meter_interval_2
  # - sensor.aeotec_dsb09104_home_energy_meter_interval_3
  - sensor.aeotec_dsb09104_home_energy_meter_power
  - sensor.aeotec_dsb09104_home_energy_meter_power_2
  - sensor.aeotec_dsb09104_home_energy_meter_power_3
  - sensor.aeotec_dsb09104_home_energy_meter_power_4
  - sensor.aeotec_dsb09104_home_energy_meter_power_5
  - sensor.aeotec_dsb09104_home_energy_meter_power_6
  # - sensor.aeotec_dsb09104_home_energy_meter_previous_reading
  # - sensor.aeotec_dsb09104_home_energy_meter_previous_reading_2
  # - sensor.aeotec_dsb09104_home_energy_meter_previous_reading_3
# F
family_room:
  name: Family Room
  icon: mdi:sofa
  entities:
  - switch.blue_rope
  - switch.red_rope
  - remote.harmony_hub
  - media_player.family_room_tv
# G
# H
# I
image_processing:
  name: Image Processors
  icon: mdi:face
  entities:
# J
# K
# L
lights:
  name: Lights
  icon: mdi:lightbuld-outline
  entities:
  - light.boys_light
  - switch.sonoff59
  - light.master_bedroom_light
  - light.hallway_light
  - light.laundry_light
  - switch.sonoff58
  - switch.sonoff57
  - switch.sonoff57b
  - switch.kitchen_lights
  - switch.sonoff56
  - switch.frontyard_lights
  - light.backyard_light
  - light.inside
  - light.outdoor
# M
maps:
  name: Maps
  icon: mdi:map
  entities:
  - camera.nilzete_map
  - camera.jizar_map
# N
# O
octoprint:
  name: OctoPrint
  icon: mdi:printer-3d
  entities:
  - binary_sensor.octoprint
  - binary_sensor.octoprint_printing
  - binary_sensor.octoprint_printing_error
  - sensor.octoprint
  - sensor.octoprint_actual_bed_temp
  - sensor.octoprint_actual_tool0_temp
  - sensor.octoprint_current_state
  - sensor.octoprint_job_percentage
  - sensor.octoprint_target_bed_temp
  - sensor.octoprint_target_tool0_temp
# P
players:
  name: Media Players
  icon: mdi:play
  entities:
  - media_player.plex
  - media_player.4KTV
  - media_player.kodi
  - media_player.vlc
  - media_player.googlebox
  - media_player.gameroom_speaker
  - media_player.plex_7xcleh4soojb4
  - media_player.samsung_led40_un40j5200
  - media_player.samsung_led32_un32j5303
  - media_player.family_room_tv
  - media_player.living_room_un60ju7090
  - media_media_player.plex_ab23df7e547be9a8_com_plexapp_android
  - media_player.plex_g4ov3n0cdvq9g7bp6ldxlib0
  - media_player.plex_zpcbbejvs2qek
# Q
# R
remotes:
  name: Remotes
  icon: mdi:remote
  entities:
  - remote.harmony_hub
# S
sensors:
  name: Sensors
  icon: mdi:wifi
  entities:
  - sun.sun
  - sensor.yr_symbol
  - sensor.motion_sensor_temperature
  - sensor.fastcom_download
  - cover.garage_door
  - sensor.energy
  - sensor.power
  - sensor.voltage
  - sensor.plex
ms1:  
  name: Multi Sensor 1
  entities:  
  - sensor.MS1_temperature  
  - sensor.MS1_humidity  
  - sensor.MS1_ldr  
  - sensor.MS1_pir  
  - light.MS1_led
ms2:  
  name: Multi Sensor2
  entities:  
  - sensor.MS2_temperature  
  - sensor.MS2_humidity  
  - sensor.MS2_ldr  
  - sensor.MS2_pir  
  - light.MS2_led
ms3:  
  name: Multi Sensor 3
  entities:  
  - sensor.MS3_temperature  
  - sensor.MS3_humidity  
  - sensor.MS3_ldr  
  - sensor.MS3_pir  
  - light.MS3_led
ms4:  
  name: Multi Sensor 4
  entities:  
  - sensor.MS4_temperature  
  - sensor.MS4_humidity  
  - sensor.MS4_ldr  
  - sensor.MS4_pir  
  - light.MS4_led
switches:
  name: Switches
  icon: mdi:dip-switch
  entities:
  - switch.sonoff50
  - switch.sonoff51
  - switch.sonoff52
  - switch.siren
  - switch.sonoff53
  - switch.sonoff54
  - switch.sonoff55
  - switch.sonoff56
  - sensor.energy
  - sensor.power
  - sensor.voltage
  - sensor.power_factor
# T
time:
  name: Time
  icon: mdi:clock
  entities:
  - sensor.time
  - sensor.date
  - sensor.speedtest_download
temperature:
  name: Temperatures
  icon: mdi:thermometer
  entities:
  - sensor.dark_sky_temperature
  - sensor.motion_sensor_temperature
  - sensor.ms1_temperature
  - sensor.MS2_temperature 
  - sensor.ms3_temperature
  - sensor.ms4_temperature
tracker:
  name: Trackers
  icon: mdi:map
  entities:
  - sensor.jizar
  - sensor.nil
  - sensor.scarlett
  - sensor.nenem
# U
# V
# X
# W
weather:
 name: Dark Sky Weather
 icon: mdi:cloud
 entities:
 - sensor.dark_sky_nearest_storm_distance
 - sensor.dark_sky_summary
 - sensor.dark_sky_temperature
 - sensor.dark_sky_humidity
 - sensor.dark_sky_pressure
 - sensor.dark_sky_visibility
 - sensor.dark_sky_wind_speed
 - sensor.dark_sky_wind_bearing
 - sensor.dark_sky_ozone
# Y
# Z
zones:
  name: Zones
  entities:
    - sensor.template_last_motion
    - binary_sensor.floorplan