- platform: mqtt_json  
  name: "MS1 LED"  
  state_topic: "bruh/sensornode1"  
  command_topic: "bruh/sensornode1/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0
  
- platform: mqtt_json  
  name: "MS2 LED"  
  state_topic: "jizar/ms2"  
  command_topic: "jizar/ms2/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 
  
- platform: mqtt_json  
  name: "MS3 LED"  
  state_topic: "jizar/ms3"  
  command_topic: "jizar/ms3/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0  
  
- platform: mqtt_json  
  name: "MS4 LED"  
  state_topic: "jizar/ms4"  
  command_topic: "jizar/ms4/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0  