##########################################################
########################   KODIS  ########################
##########################################################

- platform: kodi
  host: 192.168.1.11
  
##########################################################
########################   TVS   #########################
##########################################################

- platform: samsungtv
  name: 4KTV
  host: 192.168.1.12
  port: 8001
  #timeout: 0
  mac: !secret 4ktvmac

##########################################################
######################   SERVERS   #######################
##########################################################

# PLEX
- platform: plex
  entity_namespace: 'plex'
  include_non_clients: true
  scan_interval: 5
  show_all_controls: false
  use_custom_entity_ids: true
  use_episode_art: true
  