##########################################################
########################   KODIS  ########################
##########################################################
 
# Family Room
- platform: kodi
  name: Daddy's Kodi
  host: 192.168.1.100
  port: 8085
#
# Scarlett
- platform: kodi
  host: 192.168.1.28
  name: Scarlett's Kodi
#
##########################################################
########################   TVS   #########################
##########################################################

# GOOGLES
- platform: cast

# SMART 4K TV
- platform: samsungtv
  host: 192.168.1.7
  port: 8001
  name: 4K UN60JU7090
  mac: 14:bb:6e:56:08:43
#
##########################################################
######################   SERVERS   #######################
##########################################################

# PLEX
- platform: plex
  entity_namespace: 'plex'
  include_non_clients: true
  scan_interval: 5
  show_all_controls: false
  use_custom_entity_ids: true
  use_episode_art: true