##########################################################
########################   KODIS  ########################
##########################################################

#Family Room
- platform: kodi
  name: Daddy's Kodi
  host: 192.168.1.100
  port: 8085
  

#Scarlett
- platform: kodi
  host: 192.168.1.28
  name: Scarlett's Kodi
#
##########################################################
########################   TVS   #########################
##########################################################

# GOOGLES
- platform: cast

# SMART 4K TV
- platform: samsungtv
  host: 192.168.1.101
  name: 4K TV 60