#################################################################################
##################################   TOP SENSORS   ##############################
#################################################################################

- platform: yr
  name: Weather
#
- platform: speedtest
  name: Internet
  monitored_conditions:
    - download
#
- platform: time_date
  display_options:
    - 'time'
    - 'date'
#################################################################################
##################################      MAIL       ##############################
#################################################################################
#
- platform: usps
  name: 'USPS'
  username: !secret uspsuser
  password: !secret uspspass
- platform: ups
  name: 'UPS'
  username: !secret upsuser
  password: !secret upspass
- platform: fedex
  name: 'Fedex'
  username: !secret upsuser
  password: !secret upspass
- platform: template
  sensors:
    packages_in_transit:
      friendly_name: "Packages in Transit"
      value_template: >
        {% macro in_transit(sensor) %}
          {{sensor.state|int - delivered(sensor)|int}}
        {% endmacro %}
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
             0
          {% endif %}
        {% endmacro %}
        {{in_transit(states.sensor.usps_packages)|int + in_transit(states.sensor.ups)|int + in_transit(states.sensor.fedex)|int}}
    deliveries_today:
      friendly_name: "Today's Deliveries"
      value_template: >
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
             0
          {% endif %}
        {% endmacro %}
        {{delivered(states.sensor.usps_packages)|int + delivered(states.sensor.ups)|int + delivered(states.sensor.fedex)|int}}
#
#################################################################################
################################                   ##############################
#################################################################################
#
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
#

- platform: google_geocode
  name: Nil
  #api_key: !secret nilkey
  origin: device_tracker.jizar_nil
  options: both
  display_zone: show
- platform: google_geocode
  name: Jizar
  #api_key: !secret jizarkey
  origin: device_tracker.jizar_jizar
  options: both
  display_zone: show
- platform: google_geocode
  name: Scarlett
  #api_key: !secret jizarkey
  origin: device_tracker.scarlett
  options: both
  display_zone: show
  
- platform: template
  sensors:
    template_last_motion:
      friendly_name: 'Last Motion'
      value_template: >
        {%- set sensors = [states.binary_sensor.motion_sensor_motion] %}
        {% for sensor in sensors %}
          {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
            {{ sensor.name }}
          {% endif %}
        {% endfor %}
    nilspin:
      friendly_name: 'Nil Spinner'
      value_template: '{{ states.device_tracker.jizar_nil.state }}'
    jizarspin:
      friendly_name: 'Jizar Spinner'
      value_template: '{{ states.device_tracker.jizar_jizar.state }}'
    nilspin2:
      friendly_name: 'Nil Spinner2'
      value_template: '{{ states.device_tracker.jizar_nil.state }}'
    jizarspin2:
      friendly_name: 'Jizar Spinner2'
      value_template: '{{ states.device_tracker.jizar_jizar.state }}'
    jizarcar:
      friendly_name: 'Jizar car'
      value_template: '{{ states.device_tracker.jizar_jizar.state }}'
    nilcar:
      friendly_name: 'Nil Car'
      value_template: '{{ states.device_tracker.jizar_nil.state }}'
        
- platform: darksky
  api_key: !secret darkskyapi
  monitored_conditions:
    - summary
    - nearest_storm_distance
    - wind_speed
    - temperature
    - humidity
    - pressure
    - visibility